# 獲得所有最新消息
GET http://localhost:8080/news
Content-Type: application/json

###

# 獲得一筆最新消息
GET http://localhost:8080/news/{newsId}
Content-Type: application/json

###

# 新增一筆最新消息
POST http://localhost:8080/news
Content-Type: application/json

###

# 修改一筆最新消息
PUT http://localhost:8080/news/{newsId}
Content-Type: application/json

###

# 刪除一筆最新消息
DELETE http://localhost:8080/news/{newsId}
Content-Type: application/json